# Generated by Django 4.1.1 on 2022-09-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khoahoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='khoahoc',
            old_name='tenkhoahoc',
            new_name='ten_khoa_hoc',
        ),
        migrations.RenameField(
            model_name='khoahoc',
            old_name='urlanh',
            new_name='url_anh',
        ),
    ]
