# Generated by Django 4.1.1 on 2022-09-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khoahoc', '0002_rename_tenkhoahoc_khoahoc_ten_khoa_hoc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelKhoaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_level', models.CharField(max_length=50)),
                ('khoa_hoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoahoc.khoahoc')),
            ],
        ),
        migrations.CreateModel(
            name='MonHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_hoc', models.CharField(max_length=50)),
                ('url_anh', models.CharField(max_length=100)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khoahoc.levelkhoahoc')),
            ],
        ),
    ]
