# Generated by Django 4.1.1 on 2022-10-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoahoc', '0004_baihoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baihoc',
            name='oder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='baihoc',
            name='video_id',
            field=models.CharField(max_length=50),
        ),
    ]
