# Generated by Django 4.1.1 on 2022-11-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('khoahoc', '0005_alter_baihoc_oder_alter_baihoc_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baihoc',
            name='monhoc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='khoahoc.monhoc'),
        ),
    ]
