# Generated by Django 4.1.1 on 2022-10-30 08:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_alter_chat_mess_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mess_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 14, 0, 149887)),
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='mess',
            field=models.CharField(default='', max_length=200),
        ),
    ]
