# Generated by Django 4.1.1 on 2022-10-30 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chat_mess_user_chat_message_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='mess',
            new_name='mess_text',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_my_messages',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 30, 15, 29, 32, 69972)),
        ),
    ]
