# Generated by Django 4.1.1 on 2022-11-13 07:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_message_date_adminanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminanswer',
            name='id_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 14, 37, 23, 914684)),
        ),
    ]
