# Generated by Django 4.1.1 on 2022-11-13 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_adminanswer_id_admin_chat_id_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='message_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 13, 15, 21, 55, 541931)),
        ),
    ]
