# Generated by Django 4.1.1 on 2022-10-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='asdads',
            field=models.CharField(max_length=23, null=True),
        ),
    ]
